// Code generated by api/cmd/gen-relationships. DO NOT EDIT.
//
// Source of truth: api/configs/relationship-types.yaml
// Run `make generate-relationships` to regenerate.

package asset

// =============================================================================
// Relationship Type Constants
// =============================================================================
//
// These constants are generated from configs/relationship-types.yaml.
// Add a new type by editing the YAML and running the codegen — never
// add constants here by hand.
const (
	RelTypeRunsOn RelationshipType = "runs_on"
	RelTypeDeployedTo RelationshipType = "deployed_to"
	RelTypeContains RelationshipType = "contains"
	RelTypeExposes RelationshipType = "exposes"
	RelTypeMemberOf RelationshipType = "member_of"
	RelTypeResolvesTo RelationshipType = "resolves_to"
	RelTypeDependsOn RelationshipType = "depends_on"
	RelTypeSendsDataTo RelationshipType = "sends_data_to"
	RelTypeStoresDataIn RelationshipType = "stores_data_in"
	RelTypeAuthenticatesTo RelationshipType = "authenticates_to"
	RelTypeGrantedTo RelationshipType = "granted_to"
	RelTypeLoadBalances RelationshipType = "load_balances"
	RelTypeProtectedBy RelationshipType = "protected_by"
	RelTypeMonitors RelationshipType = "monitors"
	RelTypeManages RelationshipType = "manages"
	RelTypeOwnedBy RelationshipType = "owned_by"
)

// allRelationshipTypesGenerated is the canonical list of every valid
// relationship type, in the order they appear in the YAML.
var allRelationshipTypesGenerated = []RelationshipType{
	RelTypeRunsOn,
	RelTypeDeployedTo,
	RelTypeContains,
	RelTypeExposes,
	RelTypeMemberOf,
	RelTypeResolvesTo,
	RelTypeDependsOn,
	RelTypeSendsDataTo,
	RelTypeStoresDataIn,
	RelTypeAuthenticatesTo,
	RelTypeGrantedTo,
	RelTypeLoadBalances,
	RelTypeProtectedBy,
	RelTypeMonitors,
	RelTypeManages,
	RelTypeOwnedBy,
}

// RelationshipTypeMetadata holds the human-readable labels and the
// constraint table for a single relationship type.
type RelationshipTypeMetadata struct {
	ID          RelationshipType
	Category    string
	Direct      string
	Inverse     string
	Description string
	Constraints []RelationshipConstraint
}

// RelationshipConstraint defines one valid (sources, targets) combination
// for a relationship type. The full set of valid pairs for a type is the
// union of all its constraints.
type RelationshipConstraint struct {
	Sources []string
	Targets []string
}

// RelationshipTypeRegistry maps each relationship type to its metadata.
// Generated from the YAML — do not modify by hand.
var RelationshipTypeRegistry = map[RelationshipType]RelationshipTypeMetadata{
	RelTypeRunsOn: {
		ID:          RelTypeRunsOn,
		Category:    "attack_surface_mapping",
		Direct:      "Runs On",
		Inverse:     "Runs",
		Description: "Runtime location of a workload — service/container/website is currently executing on this compute. Use this for \"where it lives now\". For build/deploy events use Deployed To.",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "service", "api", "website" },
				Targets: []string{ "host", "container", "k8s_workload", "cloud_account" },
			},
			{
				Sources: []string{ "database" },
				Targets: []string{ "host", "container", "cloud_account" },
			},
			{
				Sources: []string{ "k8s_workload" },
				Targets: []string{ "k8s_cluster" },
			},
			{
				Sources: []string{ "container" },
				Targets: []string{ "host", "k8s_workload" },
			},
		},
	},
	RelTypeDeployedTo: {
		ID:          RelTypeDeployedTo,
		Category:    "attack_surface_mapping",
		Direct:      "Deployed To",
		Inverse:     "Has Deployment",
		Description: "Build artifact placed at a target — strictly for repos / container images / build outputs. Do NOT use this for runtime workloads (those use Runs On).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "repository", "container_image" },
				Targets: []string{ "k8s_cluster", "k8s_workload", "cloud_account", "host" },
			},
		},
	},
	RelTypeContains: {
		ID:          RelTypeContains,
		Category:    "attack_surface_mapping",
		Direct:      "Contains",
		Inverse:     "Contained By",
		Description: "Hierarchical parent-child relationship (org → app → service; cluster → namespace).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "k8s_cluster" },
				Targets: []string{ "k8s_workload" },
			},
			{
				Sources: []string{ "api_collection", "api" },
				Targets: []string{ "api_endpoint" },
			},
			{
				Sources: []string{ "host" },
				Targets: []string{ "container", "service", "database" },
			},
			{
				Sources: []string{ "repository" },
				Targets: []string{ "container_image" },
			},
			{
				Sources: []string{ "network" },
				Targets: []string{ "host", "cloud_account", "load_balancer" },
			},
			{
				Sources: []string{ "cloud_account" },
				Targets: []string{ "host", "database", "k8s_cluster", "network", "storage", "serverless" },
			},
		},
	},
	RelTypeExposes: {
		ID:          RelTypeExposes,
		Category:    "attack_surface_mapping",
		Direct:      "Exposes",
		Inverse:     "Exposed By",
		Description: "Asset exposes an access surface (api/service → port/endpoint/public interface).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "host", "k8s_workload", "container" },
				Targets: []string{ "api_endpoint", "service", "api" },
			},
			{
				Sources: []string{ "domain" },
				Targets: []string{ "website", "api", "service" },
			},
			{
				Sources: []string{ "load_balancer" },
				Targets: []string{ "api", "service", "website" },
			},
		},
	},
	RelTypeMemberOf: {
		ID:          RelTypeMemberOf,
		Category:    "attack_surface_mapping",
		Direct:      "Member Of",
		Inverse:     "Has Member",
		Description: "Membership in a group or collection (user → group; host → cluster; namespace → cluster).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "host", "container", "k8s_workload" },
				Targets: []string{ "k8s_cluster", "network" },
			},
			{
				Sources: []string{ "service", "api" },
				Targets: []string{ "network" },
			},
		},
	},
	RelTypeResolvesTo: {
		ID:          RelTypeResolvesTo,
		Category:    "attack_surface_mapping",
		Direct:      "Resolves To",
		Inverse:     "Resolved By",
		Description: "DNS resolution (domain/subdomain → IP/CDN/load balancer).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "domain" },
				Targets: []string{ "ip_address", "load_balancer", "cloud_account", "host" },
			},
		},
	},
	RelTypeDependsOn: {
		ID:          RelTypeDependsOn,
		Category:    "attack_path_analysis",
		Direct:      "Depends On",
		Inverse:     "Used By",
		Description: "A needs B to function (service → database; web_app → api).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "service", "api", "website" },
				Targets: []string{ "database", "api", "service", "credential" },
			},
			{
				Sources: []string{ "k8s_workload" },
				Targets: []string{ "container_image", "database", "api", "service" },
			},
			{
				Sources: []string{ "mobile" },
				Targets: []string{ "api", "service" },
			},
		},
	},
	RelTypeSendsDataTo: {
		ID:          RelTypeSendsDataTo,
		Category:    "attack_path_analysis",
		Direct:      "Sends Data To",
		Inverse:     "Receives Data From",
		Description: "Data flow in-transit (service → service; producer → queue).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "service", "api", "website", "mobile" },
				Targets: []string{ "database", "api", "service", "cloud_account" },
			},
			{
				Sources: []string{ "database" },
				Targets: []string{ "database" },
			},
		},
	},
	RelTypeStoresDataIn: {
		ID:          RelTypeStoresDataIn,
		Category:    "attack_path_analysis",
		Direct:      "Stores Data In",
		Inverse:     "Stores Data For",
		Description: "Data at-rest (service/app → database/bucket/data store).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "service", "api", "website" },
				Targets: []string{ "database", "storage", "cloud_account" },
			},
			{
				Sources: []string{ "k8s_workload" },
				Targets: []string{ "database", "storage" },
			},
		},
	},
	RelTypeAuthenticatesTo: {
		ID:          RelTypeAuthenticatesTo,
		Category:    "attack_path_analysis",
		Direct:      "Authenticates To",
		Inverse:     "Authenticates",
		Description: "Authentication relationship (user/service → IdP/app/api).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "api", "service", "website", "mobile" },
				Targets: []string{ "identity_provider", "service", "api" },
			},
			{
				Sources: []string{ "k8s_workload" },
				Targets: []string{ "identity_provider", "service" },
			},
		},
	},
	RelTypeGrantedTo: {
		ID:          RelTypeGrantedTo,
		Category:    "attack_path_analysis",
		Direct:      "Granted To",
		Inverse:     "Has Grant",
		Description: "IAM privilege (role/policy → principal/resource).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "credential", "service" },
				Targets: []string{ "cloud_account", "database", "api", "service", "k8s_cluster" },
			},
		},
	},
	RelTypeLoadBalances: {
		ID:          RelTypeLoadBalances,
		Category:    "attack_path_analysis",
		Direct:      "Load Balances",
		Inverse:     "Load Balanced By",
		Description: "Traffic distribution (load_balancer → service/web_app).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "load_balancer", "service", "cloud_account" },
				Targets: []string{ "host", "k8s_workload", "service", "container" },
			},
		},
	},
	RelTypeProtectedBy: {
		ID:          RelTypeProtectedBy,
		Category:    "control_and_ownership",
		Direct:      "Protected By",
		Inverse:     "Protects",
		Description: "Security control (web_app → WAF; host → EDR; cloud → CSPM).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "website", "api", "service" },
				Targets: []string{ "load_balancer", "service" },
			},
			{
				Sources: []string{ "host", "compute" },
				Targets: []string{ "service" },
			},
			{
				Sources: []string{ "cloud_account" },
				Targets: []string{ "service" },
			},
		},
	},
	RelTypeMonitors: {
		ID:          RelTypeMonitors,
		Category:    "control_and_ownership",
		Direct:      "Monitors",
		Inverse:     "Monitored By",
		Description: "Observability (SIEM/EDR/APM → asset).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "service" },
				Targets: []string{ "host", "k8s_cluster", "cloud_account", "api", "service", "database", "network" },
			},
		},
	},
	RelTypeManages: {
		ID:          RelTypeManages,
		Category:    "control_and_ownership",
		Direct:      "Manages",
		Inverse:     "Managed By",
		Description: "Control-plane management (cloud_account/IAM → resource/workload).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "cloud_account" },
				Targets: []string{ "host", "database", "k8s_cluster", "network", "load_balancer" },
			},
			{
				Sources: []string{ "k8s_cluster" },
				Targets: []string{ "k8s_workload", "container" },
			},
		},
	},
	RelTypeOwnedBy: {
		ID:          RelTypeOwnedBy,
		Category:    "control_and_ownership",
		Direct:      "Owned By",
		Inverse:     "Owns",
		Description: "Accountability (asset → team/owner).",
		Constraints: []RelationshipConstraint{
			{
				Sources: []string{ "domain", "website", "service", "repository", "cloud_account", "host", "database", "api", "mobile", "k8s_cluster" },
				Targets: []string{ "service" },
			},
		},
	},
}

// RelationshipCategory holds metadata about a relationship type category.
type RelationshipCategory struct {
	ID   string
	Name string
}

// RelationshipCategories is the ordered list of categories for the UI.
var RelationshipCategories = []RelationshipCategory{
	{ID: "attack_surface_mapping", Name: "Attack Surface Mapping"},
	{ID: "attack_path_analysis", Name: "Attack Path Analysis"},
	{ID: "control_and_ownership", Name: "Control & Ownership"},
}
