#!/usr/bin/env bash
# shellcheck source-path=SCRIPTDIR
# cut-release.sh: build release/vX.Y.Z, the branch a release PR merges into
# main (api/docs/rfcs/RFC-037 §4.2, §4.3).
#
#   cut-release.sh --version vX.Y.Z --sha SHA [--push]                 (train)
#   cut-release.sh --version vX.Y.Z --mode hotfix --picks "SHA ..." [--push]
#
#   --remote NAME   default origin;  --main BRANCH  default main
#   --repo DIR      the clone to work in (default .)
#
# Train: the branch is SHA (a develop commit) plus one `merge -s ours` commit
# that records main as a parent. Its tree is SHA's tree byte for byte, and it
# merges into main cleanly whatever merge button is used: main's squashed
# release commits are no longer conflicts. (api/scripts/release-branch.sh is
# the older, interactive form of the same thing.)
#
# `-s ours` discards main's side, so it is only honest when develop already has
# everything main has. Checked per file: a file on main that is missing at SHA
# is fine when develop deleted it (a deliberate removal ships with the
# release); a file develop never had is a fix made on main alone, and the cut
# is refused rather than silently dropping it.
#
# Hotfix: the branch is the last release tag plus the picked commits,
# cherry-picked with -x in the order given.
#
# Prints KEY=VALUE lines: BRANCH, HEAD, BASE.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$HERE/lib.sh"

VERSION=""
SHA=""
MODE="train"
PICKS=""
PUSH=0
REMOTE="origin"
MAIN="main"
REPO="."
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) VERSION="$2"; shift ;;
    --sha) SHA="$2"; shift ;;
    --mode) MODE="$2"; shift ;;
    --picks) PICKS="$2"; shift ;;
    --push) PUSH=1 ;;
    --remote) REMOTE="$2"; shift ;;
    --main) MAIN="$2"; shift ;;
    --repo) REPO="$2"; shift ;;
    -h|--help) awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); if ($0 !~ /^shellcheck/) print; next } NR > 1 { exit }' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

die() { echo "REFUSING: $*" >&2; exit 1; }
g() { git -C "$REPO" "$@"; }

rel_is_version "$VERSION" || { echo "--version must be vX.Y.Z, got '$VERSION'" >&2; exit 2; }
[[ "$MODE" == train || "$MODE" == hotfix ]] || { echo "--mode must be train or hotfix" >&2; exit 2; }
BRANCH="release/$VERSION"

g fetch --quiet --tags "$REMOTE" "+refs/heads/*:refs/remotes/$REMOTE/*"
main_ref="refs/remotes/$REMOTE/$MAIN"
g rev-parse -q --verify "$main_ref" >/dev/null || die "$REMOTE/$MAIN does not exist"

last="$(rel_latest_tag "$REPO")"
if [[ -n "$last" ]] && ! rel_version_gt "$VERSION" "$last"; then
  die "$VERSION is not greater than the last release $last"
fi
g rev-parse -q --verify "refs/tags/$VERSION" >/dev/null && die "tag $VERSION already exists"
if g ls-remote --exit-code --heads "$REMOTE" "$BRANCH" >/dev/null 2>&1; then
  die "$REMOTE/$BRANCH already exists; delete it or pick another version (this script never force-pushes)"
fi

worktree="$(mktemp -d)"
cleanup() {
  g worktree remove --force "$worktree" >/dev/null 2>&1 || true
  rm -rf "$worktree"
}
trap cleanup EXIT

if [[ "$MODE" == train ]]; then
  [[ -n "$SHA" ]] || { echo "--sha is required for a train" >&2; exit 2; }
  SHA="$(g rev-parse --verify "$SHA^{commit}")"

  refused=()
  kept_deleted=()
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    if [[ -n "$(g log -1 --format=%H --diff-filter=D "$SHA" -- "$path")" ]]; then
      kept_deleted+=("$path")
    else
      refused+=("$path")
    fi
  done < <(g diff --no-renames --name-only --diff-filter=A "$SHA" "$main_ref")
  if [[ ${#refused[@]} -gt 0 ]]; then
    {
      echo "REFUSING: ${#refused[@]} file(s) exist on $MAIN but were never on develop:"
      printf '  %s\n' "${refused[@]}"
      echo "-s ours would silently drop them. Bring them to develop first (merge or cherry-pick)."
    } >&2
    exit 1
  fi
  for path in "${kept_deleted[@]}"; do
    echo "note: $path is on $MAIN, deleted on develop; the release removes it" >&2
  done

  g branch -f "$BRANCH" "$SHA" >/dev/null
  g worktree add --quiet "$worktree" "$BRANCH"
  git -C "$worktree" merge -s ours --no-edit "$main_ref" -m "chore(release): carry $MAIN's ancestry into $VERSION

-s ours keeps develop's tree (${SHA:0:12}) byte for byte and only records
$MAIN as a parent, so the release PR merges without false conflicts.
Generated by .github/scripts/release/cut-release.sh." >/dev/null

  [[ "$(git -C "$worktree" rev-parse 'HEAD^{tree}')" == "$(g rev-parse "$SHA^{tree}")" ]] ||
    die "the release branch's tree differs from $SHA's"
  git -C "$worktree" merge-base --is-ancestor "$main_ref" HEAD || die "$MAIN is not an ancestor after the merge"
  BASE="$SHA"
else
  [[ -n "${PICKS// /}" ]] || { echo "--picks is required for a hotfix" >&2; exit 2; }
  [[ -n "$last" ]] || die "a hotfix needs a previous release tag"
  [[ "$VERSION" == "$(rel_next_version "$last" patch)" ]] ||
    die "a hotfix of $last is $(rel_next_version "$last" patch), not $VERSION"
  g merge-base --is-ancestor "$last" "$main_ref" || die "$last is not on $MAIN"
  [[ "$(g rev-parse "$last^{tree}")" == "$(g rev-parse "$main_ref^{tree}")" ]] ||
    die "$MAIN has changed since $last; a hotfix is built on the released tree only"

  g branch -f "$BRANCH" "$last^{commit}" >/dev/null
  g worktree add --quiet "$worktree" "$BRANCH"
  for p in $PICKS; do
    if ! git -C "$worktree" cherry-pick -x "$p" >/dev/null 2>&1; then
      git -C "$worktree" cherry-pick --abort >/dev/null 2>&1 || true
      cleanup
      g branch -D "$BRANCH" >/dev/null 2>&1 || true
      die "cherry-pick of $p onto $last conflicts; backport it by hand"
    fi
  done
  BASE="$(g rev-parse "$last^{commit}")"
fi

HEAD_SHA="$(git -C "$worktree" rev-parse HEAD)"
if [[ $PUSH -eq 1 ]]; then
  git -C "$worktree" push --quiet "$REMOTE" "HEAD:refs/heads/$BRANCH"
  echo "pushed $BRANCH" >&2
fi
cat <<EOF
BRANCH=$BRANCH
HEAD=$HEAD_SHA
BASE=$BASE
EOF
