package report

import (
	"bytes"
	"fmt"
	"html/template"
	"time"
)

// SummaryInput is the data for a tenant-wide findings executive summary — the
// generic (non-pentest) report a scheduled "executive_summary" report renders.
// It is built from vulnerability.FindingStats by the caller (kept dependency-free
// here so this package has no domain import).
type SummaryInput struct {
	TenantName  string
	GeneratedAt time.Time

	Total    int64
	Open     int64
	Resolved int64

	// BySeverity is keyed by lower-case severity ("critical"…"info"); missing
	// keys render as 0. Ordered for display by SeverityOrder.
	BySeverity map[string]int64

	// NewInWindow / ResolvedInWindow describe movement over the reporting window
	// (e.g. the last 7 days); WindowDays labels it. Zero values are fine.
	WindowDays       int
	NewInWindow      int64
	ResolvedInWindow int64
}

// SeverityOrder is the high→low display order for severity rows.
var SeverityOrder = []string{"critical", "high", "medium", "low", "info"}

// GenerateSummaryHTML renders the executive-summary report as a self-contained
// HTML document (inline styles, printable). All dynamic values are escaped by
// html/template, so tenant-controlled strings cannot inject markup.
func GenerateSummaryHTML(in SummaryInput) (string, error) {
	if in.GeneratedAt.IsZero() {
		return "", fmt.Errorf("GeneratedAt is required")
	}

	type sevRow struct {
		Label string
		Count int64
		Color string
		Pct   int
	}
	rows := make([]sevRow, 0, len(SeverityOrder))
	for _, s := range SeverityOrder {
		c := in.BySeverity[s]
		pct := 0
		if in.Total > 0 {
			pct = int(c * 100 / in.Total)
		}
		rows = append(rows, sevRow{
			Label: titleCase(s), Count: c, Color: severityColor(s), Pct: pct,
		})
	}

	netChange := in.NewInWindow - in.ResolvedInWindow
	trend := "flat"
	switch {
	case netChange > 0:
		trend = "up"
	case netChange < 0:
		trend = "down"
	}

	data := struct {
		SummaryInput
		Rows      []sevRow
		NetChange int64
		Trend     string
		Generated string
	}{
		SummaryInput: in,
		Rows:         rows,
		NetChange:    netChange,
		Trend:        trend,
		Generated:    in.GeneratedAt.UTC().Format("2006-01-02 15:04 MST"),
	}

	tmpl, err := template.New("summary").Parse(summaryTemplate)
	if err != nil {
		return "", fmt.Errorf("parse summary template: %w", err)
	}
	var b bytes.Buffer
	if err := tmpl.Execute(&b, data); err != nil {
		return "", fmt.Errorf("render summary: %w", err)
	}
	return b.String(), nil
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return string(s[0]-'a'+'A') + s[1:]
}

const summaryTemplate = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Security Posture — {{.TenantName}}</title>
<style>
 body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1f2937;margin:0;padding:24px;background:#f9fafb}
 .card{background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:20px;max-width:720px;margin:0 auto 16px}
 h1{font-size:20px;margin:0 0 4px} .sub{color:#6b7280;font-size:13px;margin:0 0 16px}
 .kpis{display:flex;gap:12px;flex-wrap:wrap} .kpi{flex:1;min-width:120px;border:1px solid #e5e7eb;border-radius:8px;padding:12px}
 .kpi .n{font-size:24px;font-weight:700} .kpi .l{color:#6b7280;font-size:12px}
 table{width:100%;border-collapse:collapse;margin-top:8px} td,th{padding:6px 8px;text-align:left;font-size:14px}
 .bar{height:8px;border-radius:4px} .muted{color:#6b7280;font-size:12px}
 .trend-up{color:#dc2626} .trend-down{color:#16a34a} .trend-flat{color:#6b7280}
</style></head><body>
<div class="card">
 <h1>Security Posture — {{.TenantName}}</h1>
 <p class="sub">Executive summary · generated {{.Generated}}</p>
 <div class="kpis">
  <div class="kpi"><div class="n">{{.Total}}</div><div class="l">Total findings</div></div>
  <div class="kpi"><div class="n">{{.Open}}</div><div class="l">Open</div></div>
  <div class="kpi"><div class="n">{{.Resolved}}</div><div class="l">Resolved</div></div>
 </div>
</div>
<div class="card">
 <h1 style="font-size:16px">By severity</h1>
 <table>
  {{range .Rows}}<tr>
    <td style="width:90px"><strong>{{.Label}}</strong></td>
    <td style="width:60px">{{.Count}}</td>
    <td><div class="bar" style="width:{{.Pct}}%;background:{{.Color}}"></div></td>
  </tr>{{end}}
 </table>
</div>
{{if .WindowDays}}<div class="card">
 <h1 style="font-size:16px">Last {{.WindowDays}} days</h1>
 <p>New: <strong>{{.NewInWindow}}</strong> · Resolved: <strong>{{.ResolvedInWindow}}</strong> ·
    Net: <strong class="trend-{{.Trend}}">{{if gt .NetChange 0}}+{{end}}{{.NetChange}}</strong></p>
 <p class="muted">A positive net means the backlog grew over the window.</p>
</div>{{end}}
<p class="muted" style="text-align:center">Generated by OpenCTEM</p>
</body></html>`
