DO $$
DECLARE
    t TEXT;
    tables TEXT[] := ARRAY[
        'agent_api_keys',
        'agent_audit_logs',
        'agent_metrics',
        'agents',
        'ai_triage_results',
        'api_keys',
        'asset_components',
        'asset_dedup_review',
        'asset_group_members',
        'asset_merge_log',
        'asset_owners',
        'asset_repositories',
        'asset_services',
        'asset_sources',
        'asset_state_history',
        'assignment_rules',
        'attachments',
        'attacker_profiles',
        'attack_path_nodes',
        'attack_paths',
        'attack_simulation_runs',
        'attack_simulations',
        'audit_log_chain',
        'business_service_assets',
        'business_services',
        'business_unit_assets',
        'business_units',
        'commands',
        'compensating_control_assets',
        'compensating_control_findings',
        'compliance_assessments',
        'compliance_controls',
        'compliance_finding_mappings',
        'compliance_frameworks',
        'component_licenses',
        'control_tests',
        'credentials',
        'ctem_cycle_attacker_profiles',
        'ctem_cycle_metrics',
        'ctem_cycle_scope_snapshots',
        'data_sources',
        'email_logs',
        'event_types',
        'exposure_events',
        'exposure_state_history',
        'finding_activities',
        'finding_data_flows',
        'finding_data_sources',
        'finding_flow_locations',
        'finding_group_assignments',
        'finding_regression_events',
        'finding_status_approvals',
        'finding_suppressions',
        'finding_verification_checklists',
        'group_asset_scope_rules',
        'group_members',
        'group_permissions',
        'group_permission_sets',
        'groups',
        'integration_notification_extensions',
        'integrations',
        'integration_scm_extensions',
        'licenses',
        'notification_events',
        'notification_preferences',
        'notification_reads',
        'notifications',
        'notification_state',
        'pentest_campaign_members',
        'pentest_campaigns',
        'pentest_findings',
        'pentest_finding_templates',
        'pentest_reports',
        'pentest_retests',
        'permission_set_items',
        'permission_sets',
        'permission_set_versions',
        'pipeline_runs',
        'pipeline_steps',
        'pipeline_templates',
        'priority_override_rules',
        'registration_tokens',
        'relationship_suggestions',
        'remediation_campaigns',
        'report_schedules',
        'repository_branches',
        'risk_snapshots',
        'role_permissions',
        'roles',
        'rule_bundles',
        'rule_overrides',
        'rules',
        'rule_sources',
        'rule_sync_history',
        'scanner_templates',
        'scan_profiles',
        'scan_profile_template_sources',
        'scan_schedules',
        'scan_sessions',
        'scope_exclusions',
        'scope_targets',
        'sla_policies',
        'step_runs',
        'suppression_rule_audit',
        'suppression_rules',
        'template_sources',
        'tenant_identity_providers',
        'tenant_invitations',
        'tenant_members',
        'tenant_modules',
        'tenants',
        'tenant_tool_configs',
        'threat_actor_cves',
        'threat_actors',
        'tool_categories',
        'tools',
        'user_accessible_assets',
        'user_roles',
        'webhook_deliveries',
        'webhooks',
        'workflow_edges',
        'workflow_node_runs',
        'workflow_nodes',
        'workflow_runs',
        'workflows'
    ];
BEGIN
    FOREACH t IN ARRAY tables
    LOOP
        IF EXISTS (
            SELECT 1 FROM pg_policies
             WHERE schemaname = 'public'
               AND tablename = t
               AND policyname = t || '_tenant_isolation'
        ) THEN
            EXECUTE format('DROP POLICY IF EXISTS %I ON %I', t || '_tenant_isolation', t);
        END IF;
    END LOOP;
END $$;
