-- idx_sensors_load_score (000016, renamed by 000230) is a partial index
-- WHERE status = 'active' AND health = 'healthy'. chk_sensors_health only
-- allows unknown/online/offline/error, so the predicate matches no row and
-- the planner can never use the index.
--
-- Recreating it with health = 'online' would not help either: no query reads
-- sensors.load_score. Sensor selection ranks candidates in Go
-- (internal/app/sensor/selector.go recomputes the score from the row's metrics
-- with the configured weights, deliberately not trusting the stored column),
-- and every SQL candidate query orders by current_jobs / total_scans. An index
-- nobody reads is only write cost on every heartbeat (load_score is rewritten
-- each time), so it is dropped. If a query ever orders by load_score, add the
-- index with that query, using health = 'online'.
DROP INDEX CONCURRENTLY IF EXISTS idx_sensors_load_score;
