DROP INDEX CONCURRENTLY IF EXISTS idx_approvals_finding_status;
DROP INDEX CONCURRENTLY IF EXISTS idx_approvals_tenant_status_created;
DROP INDEX CONCURRENTLY IF EXISTS idx_assignment_rules_tenant_active_priority;
