// Command gen-relationships reads configs/relationship-types.yaml and emits
// generated source files for both the Go backend and the TypeScript frontend.
//
// Usage:
//
//	cd api && go run ./cmd/gen-relationships
//
// Or via the Makefile target:
//
//	make generate-relationships
//
// The YAML file is the SINGLE SOURCE OF TRUTH for the asset relationship type
// registry. The generated files (relationship_types_generated.go on the Go
// side, relationship.types.generated.ts on the TS side) are committed but
// must NEVER be edited by hand — they will be overwritten on the next run.
//
// Workflow when adding a new relationship type:
//  1. Edit api/configs/relationship-types.yaml
//  2. Run `make generate-relationships`
//  3. Commit the YAML + the two generated files together
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// =============================================================================
// YAML schema
// =============================================================================

type config struct {
	Categories []category `yaml:"categories"`
	Types      []relType  `yaml:"types"`
}

type category struct {
	ID   string `yaml:"id"`
	Name string `yaml:"name"`
}

type relType struct {
	ID          string       `yaml:"id"`
	Category    string       `yaml:"category"`
	Direct      string       `yaml:"direct"`
	Inverse     string       `yaml:"inverse"`
	Description string       `yaml:"description"`
	Constraints []constraint `yaml:"constraints"`
}

type constraint struct {
	Sources []string `yaml:"sources"`
	Targets []string `yaml:"targets"`
}

// =============================================================================
// Output paths (relative to the api/ directory — main() resolves them)
// =============================================================================

const (
	yamlPath = "configs/relationship-types.yaml"
	goPath   = "pkg/domain/asset/relationship_types_generated.go"
	tsPath   = "../ui/src/features/assets/types/relationship.types.generated.ts"
)

// =============================================================================
// main
// =============================================================================

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-relationships: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := loadConfig(yamlPath)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	if err := validate(cfg); err != nil {
		return fmt.Errorf("validate config: %w", err)
	}

	if err := writeGoFile(cfg, goPath); err != nil {
		return fmt.Errorf("write go file: %w", err)
	}

	if err := writeTSFile(cfg, tsPath); err != nil {
		return fmt.Errorf("write ts file: %w", err)
	}

	fmt.Printf("✓ Generated %d relationship types into:\n", len(cfg.Types))
	fmt.Printf("    %s\n", goPath)
	fmt.Printf("    %s\n", tsPath)
	return nil
}

func loadConfig(path string) (*config, error) {
	bytes, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg config
	if err := yaml.Unmarshal(bytes, &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// validate ensures the YAML is internally consistent before we generate
// anything. Catches typos that would otherwise produce a broken file.
func validate(cfg *config) error {
	if len(cfg.Categories) == 0 {
		return fmt.Errorf("no categories defined")
	}
	if len(cfg.Types) == 0 {
		return fmt.Errorf("no types defined")
	}

	categoryIDs := make(map[string]bool, len(cfg.Categories))
	for _, c := range cfg.Categories {
		if c.ID == "" || c.Name == "" {
			return fmt.Errorf("category with empty id or name")
		}
		if categoryIDs[c.ID] {
			return fmt.Errorf("duplicate category id %q", c.ID)
		}
		categoryIDs[c.ID] = true
	}

	typeIDs := make(map[string]bool, len(cfg.Types))
	for _, t := range cfg.Types {
		if t.ID == "" {
			return fmt.Errorf("type with empty id")
		}
		if typeIDs[t.ID] {
			return fmt.Errorf("duplicate type id %q", t.ID)
		}
		typeIDs[t.ID] = true
		if !categoryIDs[t.Category] {
			return fmt.Errorf("type %q references unknown category %q", t.ID, t.Category)
		}
		if t.Direct == "" || t.Inverse == "" {
			return fmt.Errorf("type %q has empty direct or inverse label", t.ID)
		}
		if len(t.Constraints) == 0 {
			return fmt.Errorf("type %q has no constraints", t.ID)
		}
		for i, c := range t.Constraints {
			if len(c.Sources) == 0 || len(c.Targets) == 0 {
				return fmt.Errorf("type %q constraint #%d has empty sources or targets", t.ID, i)
			}
		}
	}
	return nil
}

// =============================================================================
// Go output
// =============================================================================

const goTemplate = `// Code generated by api/cmd/gen-relationships. DO NOT EDIT.
//
// Source of truth: api/configs/relationship-types.yaml
// Run ` + "`make generate-relationships`" + ` to regenerate.

package asset

// =============================================================================
// Relationship Type Constants
// =============================================================================
//
// These constants are generated from configs/relationship-types.yaml.
// Add a new type by editing the YAML and running the codegen — never
// add constants here by hand.
const (
{{range .Types}}	RelType{{toCamel .ID}} RelationshipType = "{{.ID}}"
{{end}})

// allRelationshipTypesGenerated is the canonical list of every valid
// relationship type, in the order they appear in the YAML.
var allRelationshipTypesGenerated = []RelationshipType{
{{range .Types}}	RelType{{toCamel .ID}},
{{end}}}

// RelationshipTypeMetadata holds the human-readable labels and the
// constraint table for a single relationship type.
type RelationshipTypeMetadata struct {
	ID          RelationshipType
	Category    string
	Direct      string
	Inverse     string
	Description string
	Constraints []RelationshipConstraint
}

// RelationshipConstraint defines one valid (sources, targets) combination
// for a relationship type. The full set of valid pairs for a type is the
// union of all its constraints.
type RelationshipConstraint struct {
	Sources []string
	Targets []string
}

// RelationshipTypeRegistry maps each relationship type to its metadata.
// Generated from the YAML — do not modify by hand.
var RelationshipTypeRegistry = map[RelationshipType]RelationshipTypeMetadata{
{{range .Types}}	RelType{{toCamel .ID}}: {
		ID:          RelType{{toCamel .ID}},
		Category:    {{printf "%q" .Category}},
		Direct:      {{printf "%q" .Direct}},
		Inverse:     {{printf "%q" .Inverse}},
		Description: {{printf "%q" (trimDesc .Description)}},
		Constraints: []RelationshipConstraint{
{{range .Constraints}}			{
				Sources: []string{ {{stringList .Sources}} },
				Targets: []string{ {{stringList .Targets}} },
			},
{{end}}		},
	},
{{end}}}

// RelationshipCategory holds metadata about a relationship type category.
type RelationshipCategory struct {
	ID   string
	Name string
}

// RelationshipCategories is the ordered list of categories for the UI.
var RelationshipCategories = []RelationshipCategory{
{{range .Categories}}	{ID: {{printf "%q" .ID}}, Name: {{printf "%q" .Name}}},
{{end}}}
`

func writeGoFile(cfg *config, path string) error {
	funcs := template.FuncMap{
		"toCamel":    toCamel,
		"stringList": goStringList,
		"trimDesc":   trimDesc,
	}
	t, err := template.New("go").Funcs(funcs).Parse(goTemplate)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()
	return t.Execute(f, cfg)
}

// =============================================================================
// TS output
// =============================================================================

const tsTemplate = `// @ts-nocheck
/* eslint-disable */
//
// Code generated by api/cmd/gen-relationships. DO NOT EDIT.
//
// Source of truth: api/configs/relationship-types.yaml
// Run ` + "`make generate-relationships`" + ` (from the api/ directory) to regenerate.

import type { ExtendedAssetType } from './relationship.types'

// =============================================================================
// Relationship Type Union
// =============================================================================

export type GeneratedRelationshipType =
{{range $i, $t := .Types}}{{if $i}}
{{end}}  | '{{.ID}}'{{end}}

// =============================================================================
// Labels
// =============================================================================

export interface GeneratedRelationshipLabel {
  direct: string
  inverse: string
  description: string
  category: string
}

export const GENERATED_RELATIONSHIP_LABELS: Record<
  GeneratedRelationshipType,
  GeneratedRelationshipLabel
> = {
{{range .Types}}  {{.ID}}: {
    direct: {{printf "%q" .Direct}},
    inverse: {{printf "%q" .Inverse}},
    description: {{printf "%q" (trimDesc .Description)}},
    category: {{printf "%q" .Category}},
  },
{{end}}}

// =============================================================================
// Constraints
// =============================================================================

export interface GeneratedRelationshipConstraint {
  sourceTypes: ExtendedAssetType[]
  targetTypes: ExtendedAssetType[]
}

export const GENERATED_RELATIONSHIP_CONSTRAINTS: Record<
  GeneratedRelationshipType,
  GeneratedRelationshipConstraint[]
> = {
{{range .Types}}  {{.ID}}: [
{{range .Constraints}}    {
      sourceTypes: [{{tsStringList .Sources}}],
      targetTypes: [{{tsStringList .Targets}}],
    },
{{end}}  ],
{{end}}}

// =============================================================================
// Categories (display order)
// =============================================================================

export interface GeneratedRelationshipCategory {
  id: string
  name: string
}

export const GENERATED_RELATIONSHIP_CATEGORIES: GeneratedRelationshipCategory[] = [
{{range .Categories}}  { id: {{printf "%q" .ID}}, name: {{printf "%q" .Name}} },
{{end}}]

// =============================================================================
// Convenience: ordered ID list
// =============================================================================

export const ALL_GENERATED_RELATIONSHIP_TYPES: GeneratedRelationshipType[] = [
{{range .Types}}  '{{.ID}}',
{{end}}]
`

func writeTSFile(cfg *config, path string) error {
	funcs := template.FuncMap{
		"trimDesc":     trimDesc,
		"tsStringList": tsStringList,
	}
	t, err := template.New("ts").Funcs(funcs).Parse(tsTemplate)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()
	return t.Execute(f, cfg)
}

// =============================================================================
// Template helpers
// =============================================================================

// toCamel converts snake_case → CamelCase for Go identifier names.
//
//	"runs_on"          -> "RunsOn"
//	"sends_data_to"    -> "SendsDataTo"
//	"k8s_workload"     -> "K8sWorkload"
func toCamel(s string) string {
	parts := strings.Split(s, "_")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		out = append(out, strings.ToUpper(p[:1])+p[1:])
	}
	return strings.Join(out, "")
}

// goStringList renders a string slice as Go literal: `"a", "b", "c"`.
func goStringList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(parts, ", ")
}

// tsStringList renders a string slice as TS literal: `'a', 'b', 'c'`.
func tsStringList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = "'" + s + "'"
	}
	return strings.Join(parts, ", ")
}

// trimDesc collapses YAML "folded" multi-line descriptions into a single
// line and trims trailing whitespace, so the generated literal is clean.
func trimDesc(s string) string {
	// Replace multiple whitespace runs (including newlines) with a single space.
	fields := strings.Fields(s)
	return strings.Join(fields, " ")
}

// keep yaml import referenced in case future versions only need it
// transitively — silences unused-import errors during refactors.
var _ = yaml.Unmarshal

// keep sort referenced for the same reason — used in earlier drafts and
// likely needed again when we add stable ordering for category groups.
var _ = sort.Strings
