package sensor

// Code generated from configs/sensor-templates/*.tmpl; DO NOT EDIT BY HAND.
// The built-in templates are the fallback for a missing template file and
// must stay identical to the shipped files (TestTemplates_ShippedFilesMatchBuiltins).
// Regenerate after editing a .tmpl file:
//
//	go generate ./internal/app/sensor/

//go:generate go run ./gen_builtin_templates.go

var builtinTemplates = map[string]string{
	"yaml": `# Sensor configuration for {{slugify .Sensor.Name}}
# Generated by OpenCTEM at {{.GeneratedAt}}
#
# Save as sensor.yaml and run: openctemio-sensor -daemon -config sensor.yaml
# Environment variables (API_URL, API_KEY, SENSOR_TOOLS) override it.
#
# To customize this template, edit configs/sensor-templates/yaml.tmpl on the
# API host (/app/configs/sensor-templates/yaml.tmpl in the container image, or
# the directory set by SENSOR_CONFIG_TEMPLATES_DIR) — no frontend rebuild needed.

sensor:
  name: {{yamlQuote .Sensor.Name}}
  enable_commands: true
  heartbeat_interval: 30s

server:
  base_url: {{yamlQuote .BaseURL}}
  api_key: {{if .APIKey}}{{yamlQuote .APIKey}}{{else}}${API_KEY}{{end}}
  sensor_id: {{.Sensor.ID}}

# Results not yet accepted by the platform wait here; keep it on persistent
# storage so a restart or an outage loses nothing.
outbox:
  dir: /var/lib/openctem/outbox

# The sensor keeps its state, including the API key it renews on its own, in
# SENSOR_STATE_DIR (default /var/lib/openctem/state, else ~/.openctem). Keep
# that directory: without it the sensor starts with api_key above, which a
# renewal has retired.

scanners:
{{- with tools .Sensor.Tools}}
{{- range .}}
  - name: {{toScannerName .}}
    enabled: true
{{- end}}
{{- else}}
  - name: semgrep
    enabled: true
{{- end}}
`,
	"env": `# Environment variables for {{slugify .Sensor.Name}}
# Generated by OpenCTEM at {{.GeneratedAt}}
{{- if .APIKey}}
export API_URL={{shellQuote .BaseURL}}
export API_KEY={{shellQuote .APIKey}}
{{- else}}
# The API key is shown once, when the sensor is created or its key is rotated.
export API_URL={{shellQuote .BaseURL}}
export API_KEY='rda_...'
{{- end}}
{{- with toolList .Sensor.Tools}}
export SENSOR_TOOLS={{.}}
{{- end}}
{{- if .CACert}}
# The platform uses a private CA: install it (see the docker run instructions)
# and let the sensor trust it alongside the system roots.
export SSL_CERT_DIR=/etc/openctem/certs
{{- end}}
`,
	"docker": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": docker run
# Generated by OpenCTEM at {{.GeneratedAt}}. Run it on the host that should scan.
# Edit configs/sensor-templates/docker.tmpl on the API host to change it.
{{- if not .APIKey}}
#
# The command reads the sensor's API key from OPENCTEM_API_KEY. The key is
# shown once, when the sensor is created or its key is rotated:
#   export OPENCTEM_API_KEY='rda_...'
{{- end}}
{{- if .CACert}}

# 1. Trust the platform's certificate authority (it uses a private CA).
sudo mkdir -p /etc/openctem/certs
sudo tee /etc/openctem/certs/openctem-root-ca.crt >/dev/null <<'OPENCTEM_CA'
{{.CACert}}OPENCTEM_CA
sudo chmod 0644 /etc/openctem/certs/openctem-root-ca.crt
{{- end}}
{{- if isDaemon .Sensor}}

# {{if .CACert}}2. {{end}}Start the sensor. It connects out to the platform (no inbound port)
# and runs the scans the platform dispatches. Results that cannot be delivered
# yet wait in the {{$slug}}-outbox volume, so a restart or an outage loses nothing.
# The {{$slug}}-state volume keeps the sensor's state, including the API key
# it renews on its own: keep it with the container (a new container without it
# starts with the key above, which a renewal has retired).
docker run -d --name {{$slug}} --restart unless-stopped \
  -e API_URL={{shellQuote .BaseURL}} \
{{- if .APIKey}}
  -e API_KEY={{shellQuote .APIKey}} \
{{- else}}
  -e API_KEY="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}" \
{{- end}}
{{- with toolList .Sensor.Tools}}
  -e SENSOR_TOOLS={{.}} \
{{- end}}
{{- if .CACert}}
  -e SSL_CERT_DIR=/etc/openctem/certs \
  -v /etc/openctem/certs:/etc/openctem/certs:ro \
{{- end}}
  -v {{$slug}}-outbox:/var/lib/openctem/outbox \
  -v {{$slug}}-state:/var/lib/openctem/state \
  {{.Image}}

# Check it: docker logs -f {{$slug}}   (the Sensors page shows it online
# within a minute)
{{- else}}

# {{if .CACert}}2. {{end}}Run one scan of the current directory and send the results (CI or a
# shell). Arguments after the image replace the default command.
docker run --rm \
  -e API_URL={{shellQuote .BaseURL}} \
{{- if .APIKey}}
  -e API_KEY={{shellQuote .APIKey}} \
{{- else}}
  -e API_KEY="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}" \
{{- end}}
{{- if .CACert}}
  -e SSL_CERT_DIR=/etc/openctem/certs \
  -v /etc/openctem/certs:/etc/openctem/certs:ro \
{{- end}}
  -v "$PWD":/scan \
  {{.Image}} \
  -tool {{firstTool .Sensor.Tools}} -target /scan -push
{{- end}}
`,
	"cli": `# Sensor binary commands for {{slugify .Sensor.Name}}
# Generated by OpenCTEM at {{.GeneratedAt}}
# Download: https://github.com/openctemio/sensor/releases ({{imageTag .Image}})

export API_URL={{shellQuote .BaseURL}}
{{- if .APIKey}}
export API_KEY={{shellQuote .APIKey}}
{{- else}}
export API_KEY="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}"
{{- end}}
{{- if .CACert}}
export SSL_CERT_DIR=/etc/openctem/certs
{{- end}}

# Long-running: run the scans the platform dispatches. The sensor keeps its
# state, including the API key it renews on its own, in SENSOR_STATE_DIR
# (default /var/lib/openctem/state when writable, else ~/.openctem).
./openctemio-sensor -daemon -enable-commands{{with toolList .Sensor.Tools}} -tools {{.}}{{end}}

# One-shot: scan a directory once and send the results
./openctemio-sensor -tool {{firstTool .Sensor.Tools}} -target . -push
`,
	"compose": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": Docker Compose
# Generated by OpenCTEM at {{.GeneratedAt}}. Edit
# configs/sensor-templates/compose.tmpl on the API host to change it.
#
# In an empty directory on the host that should scan:
#   1. Put the sensor's API key in .env (kept out of this file):
{{- if .APIKey}}
#        printf '%s\n' 'OPENCTEM_API_KEY={{.APIKey}}' > .env && chmod 600 .env
{{- else}}
#        printf '%s\n' 'OPENCTEM_API_KEY=rda_...' > .env && chmod 600 .env
#      (the key is shown once, when the sensor is created or its key rotated)
{{- end}}
#   2. Save this file as compose.yaml and run: docker compose up -d
{{- if .CACert}}
#   The platform's private CA is embedded below (configs.content needs
#   Docker Compose 2.23.1 or later).
{{- end}}
services:
  sensor:
    image: {{.Image}}
    container_name: {{$slug}}
    restart: {{if isDaemon .Sensor}}unless-stopped{{else}}"no"{{end}}
{{- if not (isDaemon .Sensor)}}
    # A one-shot sensor: scans ./src once and sends the results.
    command: ["-tool", "{{firstTool .Sensor.Tools}}", "-target", "/scan", "-push"]
{{- end}}
    environment:
      API_URL: {{yamlQuote .BaseURL}}
      API_KEY: ${OPENCTEM_API_KEY:?set OPENCTEM_API_KEY in .env}
{{- with toolList .Sensor.Tools}}
      SENSOR_TOOLS: {{yamlQuote .}}
{{- end}}
{{- if .CACert}}
      SSL_CERT_DIR: /etc/openctem/certs
{{- end}}
    volumes:
      - outbox:/var/lib/openctem/outbox
{{- if isDaemon .Sensor}}
      - state:/var/lib/openctem/state
{{- end}}
{{- if not (isDaemon .Sensor)}}
      - ./src:/scan:ro
{{- end}}
{{- if .CACert}}
    configs:
      - source: openctem_ca
        target: /etc/openctem/certs/openctem-root-ca.crt
        mode: 0444
{{- end}}

volumes:
  # Results that cannot be delivered yet; a restart or an outage loses nothing.
  outbox:
{{- if isDaemon .Sensor}}
  # The sensor's state, including the API key it renews on its own. Keep it:
  # without it the sensor starts with the key in .env, which a renewal has
  # retired.
  state:
{{- end}}
{{- if .CACert}}

configs:
  openctem_ca:
    content: |
{{indent 6 .CACert}}
{{- end}}
`,
	"kubernetes": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": Kubernetes manifests
# Generated by OpenCTEM at {{.GeneratedAt}}. Edit
# configs/sensor-templates/kubernetes.tmpl on the API host to change it.
#
# Apply in the namespace the sensor should run in:
#   kubectl apply -n <namespace> -f {{$slug}}.yaml
{{- if not .APIKey}}
# Replace rda_... below with the sensor's API key first (it is shown once,
# when the sensor is created or its key is rotated).
{{- end}}
apiVersion: v1
kind: Secret
metadata:
  name: {{$slug}}
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
type: Opaque
stringData:
  api-key: {{if .APIKey}}{{.APIKey}}{{else}}rda_...{{end}}
{{- if .CACert}}
  ca.crt: |
{{indent 4 .CACert}}
{{- end}}
{{- if isDaemon .Sensor}}
---
# Results that cannot be delivered yet; a restart or an outage loses nothing.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$slug}}-outbox
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
# The sensor's state, including the API key it renews on its own (the Secret
# above keeps the key it was installed with, which a renewal retires).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$slug}}-state
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$slug}}
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  # One sensor identity (one key) and one outbox: a single replica, and the
  # old pod stops before the new one starts.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{$slug}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openctem-sensor
        app.kubernetes.io/instance: {{$slug}}
    spec:
      securityContext:
        # The image runs as uid/gid 999; this lets it write its volumes.
        fsGroup: 999
      containers:
        - name: sensor
          image: {{.Image}}
          env:
            - name: API_URL
              value: {{yamlQuote .BaseURL}}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{$slug}}
                  key: api-key
{{- with toolList .Sensor.Tools}}
            - name: SENSOR_TOOLS
              value: {{yamlQuote .}}
{{- end}}
{{- if .CACert}}
            - name: SSL_CERT_DIR
              value: /etc/openctem/certs
{{- end}}
          volumeMounts:
            - name: outbox
              mountPath: /var/lib/openctem/outbox
            - name: state
              mountPath: /var/lib/openctem/state
{{- if .CACert}}
            - name: ca
              mountPath: /etc/openctem/certs
              readOnly: true
{{- end}}
      volumes:
        - name: outbox
          persistentVolumeClaim:
            claimName: {{$slug}}-outbox
        - name: state
          persistentVolumeClaim:
            claimName: {{$slug}}-state
{{- if .CACert}}
        - name: ca
          secret:
            secretName: {{$slug}}
            items:
              - key: ca.crt
                path: openctem-root-ca.crt
{{- end}}
{{- else}}
---
# A one-shot sensor: one scan, then the Job completes. Mount what it should
# scan at /scan (the emptyDir below is a placeholder).
apiVersion: batch/v1
kind: Job
metadata:
  name: {{$slug}}-scan
  labels:
    app.kubernetes.io/name: openctem-sensor
    app.kubernetes.io/instance: {{$slug}}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openctem-sensor
        app.kubernetes.io/instance: {{$slug}}
    spec:
      restartPolicy: Never
      containers:
        - name: sensor
          image: {{.Image}}
          args: ["-tool", "{{firstTool .Sensor.Tools}}", "-target", "/scan", "-push"]
          env:
            - name: API_URL
              value: {{yamlQuote .BaseURL}}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{$slug}}
                  key: api-key
{{- if .CACert}}
            - name: SSL_CERT_DIR
              value: /etc/openctem/certs
{{- end}}
          volumeMounts:
            - name: scan
              mountPath: /scan
{{- if .CACert}}
            - name: ca
              mountPath: /etc/openctem/certs
              readOnly: true
{{- end}}
      volumes:
        - name: scan
          emptyDir: {}
{{- if .CACert}}
        - name: ca
          secret:
            secretName: {{$slug}}
            items:
              - key: ca.crt
                path: openctem-root-ca.crt
{{- end}}
{{- end}}
`,
	"helm": `{{- $slug := slugify .Sensor.Name -}}
# OpenCTEM sensor "{{$slug}}": Helm (the sensor bundled with the openctem chart)
# Generated by OpenCTEM at {{.GeneratedAt}}. Edit
# configs/sensor-templates/helm.tmpl on the API host to change it.
#
# Runs the sensor next to the platform, in the same cluster and namespace as
# the openctem release, talking to the API service directly. For a sensor in
# another network, use the Kubernetes or docker run instructions instead.
{{- if not (isDaemon .Sensor)}}
#
# The bundled sensor is a long-running one. This sensor runs one scan at a
# time (CI), so use the docker run or Kubernetes Job instructions instead.
{{- else}}
{{- if not .APIKey}}
# The key is shown once, when the sensor is created or its key is rotated:
#   export OPENCTEM_API_KEY='rda_...'
{{- end}}

# 1. Store the sensor's API key in a Secret (never in Helm values).
kubectl create secret generic {{$slug}}-key \
{{- if .APIKey}}
  --from-literal=api-key={{shellQuote .APIKey}}
{{- else}}
  --from-literal=api-key="${OPENCTEM_API_KEY:?export OPENCTEM_API_KEY first}"
{{- end}}

# 2. Turn the bundled sensor on (release "openctem"; use yours).
helm upgrade openctem openctem/openctem --reuse-values \
  --set sensor.enabled=true \
  --set sensor.mode=daemon \
  --set sensor.image.tag={{imageTag .Image}} \
  --set sensor.existingSecret={{$slug}}-key \
{{- with toolList .Sensor.Tools}}
  --set-string 'sensor.tools={{replaceComma .}}' \
{{- end}}
  --set sensor.outbox.persistence.enabled=true \
  --set sensor.state.persistence.enabled=true
{{- end}}
`,
}
