#!/usr/bin/env bash
#
# check-openapi.sh — the committed OpenAPI spec must equal a fresh regeneration.
#
# WHY: api/openapi/swagger.yaml is generated by `swag` from the `// @Router`
# annotations on the handlers, but nothing ever verified that. The committed
# file drifted for long enough that it stopped describing this server at all:
#
#   • 30 documented paths (/admin/platform-agents, /admin/bootstrap-tokens,
#     /plans, /tenants/{id}/subscription, ...) had no handler and no route
#     anywhere in the repository — leftovers from a closed-source era.
#   • 40 real endpoints were missing entirely, including the whole
#     /notifications API and GET /auth/providers.
#
# That is not a documentation problem. The UI is written against this file, so
# a stale entry becomes a client calling an endpoint that does not exist
# (GET /me/event-types) and a missing entry becomes a feature no client can
# discover (six notification event types with no checkbox, sla_breach
# notifying nobody).
#
# This script regenerates the spec into a temporary directory and diffs it
# against the committed one. It deliberately has NO conditions: no event_name
# gate, no base-ref resolution, no "skip if the tool is missing". A check that
# can silently not run is worse than no check, and this repository has shipped
# that failure mode more than once. If swag cannot be installed, the script
# fails.
#
# Usage:
#   scripts/check-openapi.sh          # verify (CI + local)
#
# To fix a failure:
#   make swagger && git add api/openapi/swagger.yaml
#
# Exit codes: 0 = spec matches the annotations, 1 = drift, 2 = tooling error.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC="api/openapi/swagger.yaml"
COMMITTED="$REPO_ROOT/$SPEC"

# Pinned so an upstream swag release cannot turn every PR red (or, worse, quietly
# change the contract). Bump this and the Makefile's swagger-install together,
# then re-run `make swagger`.
SWAG_VERSION="v1.16.4"

if [ ! -f "$COMMITTED" ]; then
  echo "check-openapi: $SPEC is missing from the repository." >&2
  exit 2
fi

# --- resolve swag at the pinned version -------------------------------------

swag_bin=""
if command -v swag >/dev/null 2>&1 && swag --version 2>/dev/null | grep -qF "$SWAG_VERSION"; then
  swag_bin="$(command -v swag)"
else
  echo "check-openapi: installing swag $SWAG_VERSION ..."
  if ! GOWORK=off GOFLAGS=-mod=mod go install "github.com/swaggo/swag/cmd/swag@$SWAG_VERSION" >&2; then
    echo "check-openapi: could not install swag $SWAG_VERSION." >&2
    exit 2
  fi
  gobin="$(go env GOBIN)"
  [ -n "$gobin" ] || gobin="$(go env GOPATH)/bin"
  swag_bin="$gobin/swag"
fi

if [ ! -x "$swag_bin" ]; then
  echo "check-openapi: swag not executable at '$swag_bin'." >&2
  exit 2
fi

# --- regenerate into a scratch directory ------------------------------------

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

# --parseDependency makes swag read the source of dependency packages to resolve
# types. When a package is missing from the module cache it does not fail — it
# silently emits a degraded schema, e.g. `type: integer` where the real type is
# int64 and the full run produces `format: int64` too.
#
# That is worse than a hard error for a gate like this one: a developer with a
# warm cache commits the full spec, CI regenerates with a cold cache, and the
# two disagree over dozens of lines that describe the same types. It happened on
# the very first run of this gate.
#
# Downloading here rather than in the workflow keeps `make swagger-check` and CI
# producing the same bytes, which is the only property that makes a
# generated-artifact gate worth having.
if ! (cd "$REPO_ROOT" && GOWORK=off go mod download) >/dev/null 2>&1; then
  echo "check-openapi: go mod download failed; --parseDependency would silently" >&2
  echo "produce a degraded spec and the comparison would be meaningless." >&2
  exit 2
fi

if ! (cd "$REPO_ROOT" && GOWORK=off "$swag_bin" init \
        --generalInfo cmd/server/main.go \
        --output "$tmpdir" \
        --outputTypes yaml \
        --parseDependency) >"$tmpdir/swag.log" 2>&1; then
  echo "check-openapi: swag init failed:" >&2
  cat "$tmpdir/swag.log" >&2
  exit 2
fi

if [ ! -f "$tmpdir/swagger.yaml" ]; then
  echo "check-openapi: swag produced no swagger.yaml." >&2
  cat "$tmpdir/swag.log" >&2
  exit 2
fi

# --- compare -----------------------------------------------------------------

if diff -u "$COMMITTED" "$tmpdir/swagger.yaml" >"$tmpdir/spec.diff" 2>&1; then
  echo "check-openapi: $SPEC matches the handler annotations."
  exit 0
fi

{
  echo
  echo "────────────────────────────────────────────────────────────────────────────"
  echo "OpenAPI spec is out of date."
  echo
  echo "$SPEC does not match what swag $SWAG_VERSION generates from the"
  echo "// @Router annotations in internal/infra/http/handler/."
  echo
  echo "The spec is a generated artifact and the UI generates its API types from"
  echo "it, so hand-editing it — or changing a handler's annotations without"
  echo "regenerating — silently ships a client written against a server that does"
  echo "not exist."
  echo
  echo "Fix:"
  echo "    make swagger"
  echo "    git add $SPEC"
  echo
  echo "Diff (committed → regenerated), first 200 lines:"
  echo "────────────────────────────────────────────────────────────────────────────"
  head -n 200 "$tmpdir/spec.diff"
  lines="$(wc -l <"$tmpdir/spec.diff")"
  if [ "$lines" -gt 200 ]; then
    echo "... ($((lines - 200)) more diff lines)"
  fi
} >&2

exit 1
