#!/usr/bin/env bash
#
# check-openapi.sh — the committed OpenAPI spec must equal a fresh regeneration.
#
# WHY: api/openapi/swagger.yaml is generated by `swag` from the `// @Router`
# annotations on the handlers, but nothing ever verified that. The committed
# file drifted for long enough that it stopped describing this server at all:
#
#   • 30 documented paths (/admin/platform-agents, /admin/bootstrap-tokens,
#     /plans, /tenants/{id}/subscription, ...) had no handler and no route
#     anywhere in the repository — leftovers from a closed-source era.
#   • 40 real endpoints were missing entirely, including the whole
#     /notifications API and GET /auth/providers.
#
# That is not a documentation problem. The UI is written against this file, so
# a stale entry becomes a client calling an endpoint that does not exist
# (GET /me/event-types) and a missing entry becomes a feature no client can
# discover (six notification event types with no checkbox, sla_breach
# notifying nobody).
#
# This script regenerates the spec into a temporary directory and diffs it
# against the committed one. It deliberately has NO conditions: no event_name
# gate, no base-ref resolution, no "skip if the tool is missing". A check that
# can silently not run is worse than no check, and this repository has shipped
# that failure mode more than once. If swag cannot be installed, the script
# fails.
#
# Usage:
#   scripts/check-openapi.sh          # verify (CI + local)
#
# To fix a failure:
#   make swagger && git add api/openapi/swagger.yaml
#
# Exit codes: 0 = spec matches the annotations, 1 = drift, 2 = tooling error.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC="api/openapi/swagger.yaml"
COMMITTED="$REPO_ROOT/$SPEC"

# Pinned so an upstream swag release cannot turn every PR red (or, worse, quietly
# change the contract). Bump this and the Makefile's swagger-install together,
# then re-run `make swagger`.
SWAG_VERSION="v1.16.4"

if [ ! -f "$COMMITTED" ]; then
  echo "check-openapi: $SPEC is missing from the repository." >&2
  exit 2
fi

# --- resolve swag at the pinned version -------------------------------------

swag_bin=""
if command -v swag >/dev/null 2>&1 && swag --version 2>/dev/null | grep -qF "$SWAG_VERSION"; then
  swag_bin="$(command -v swag)"
else
  echo "check-openapi: installing swag $SWAG_VERSION ..."
  if ! GOWORK=off GOFLAGS=-mod=mod go install "github.com/swaggo/swag/cmd/swag@$SWAG_VERSION" >&2; then
    echo "check-openapi: could not install swag $SWAG_VERSION." >&2
    exit 2
  fi
  gobin="$(go env GOBIN)"
  [ -n "$gobin" ] || gobin="$(go env GOPATH)/bin"
  swag_bin="$gobin/swag"
fi

if [ ! -x "$swag_bin" ]; then
  echo "check-openapi: swag not executable at '$swag_bin'." >&2
  exit 2
fi

# --- regenerate into a scratch directory ------------------------------------

# swag runs with --parseDependency, so it walks into the dependency packages to
# resolve types declared outside this module. If those packages are not in the
# module cache it does not fail — it silently emits a less-resolved schema:
# `format: int64` disappears from integers whose Go type comes from a
# dependency, and x-enum-descriptions vanishes for enums declared in one. That
# produced a spec that differed from the committed file on a clean CI runner
# while matching perfectly on a developer machine with a warm cache. Populate
# the cache first so the generator is reproducible.
if ! (cd "$REPO_ROOT" && GOWORK=off go mod download all) >&2; then
  echo "check-openapi: go mod download failed — swag needs the dependency" >&2
  echo "               packages in the module cache to resolve types." >&2
  exit 2
fi

# Fail loudly if a dependency swag must read is not actually extracted on disk.
# `go mod download` succeeding is not proof: with module-graph pruning it can
# leave a module's source unextracted, and swag then degrades in silence.
for mod in github.com/openctemio/ctis github.com/openctemio/sdk-go; do
  dir="$( (cd "$REPO_ROOT" && GOWORK=off go list -m -f '{{.Dir}}' "$mod") 2>/dev/null || true)"
  if [ -z "$dir" ] || [ ! -d "$dir" ]; then
    echo "check-openapi: $mod source is not on disk (go list -m gave '$dir')." >&2
    echo "               swag --parseDependency would silently emit a degraded" >&2
    echo "               schema. Run: GOWORK=off go mod download all" >&2
    exit 2
  fi
done

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

if ! (cd "$REPO_ROOT" && GOWORK=off "$swag_bin" init \
        --generalInfo cmd/server/main.go \
        --output "$tmpdir" \
        --outputTypes yaml \
        --parseDependency) >"$tmpdir/swag.log" 2>&1; then
  echo "check-openapi: swag init failed:" >&2
  cat "$tmpdir/swag.log" >&2
  exit 2
fi

if [ ! -f "$tmpdir/swagger.yaml" ]; then
  echo "check-openapi: swag produced no swagger.yaml." >&2
  cat "$tmpdir/swag.log" >&2
  exit 2
fi

# --- compare -----------------------------------------------------------------

if diff -u "$COMMITTED" "$tmpdir/swagger.yaml" >"$tmpdir/spec.diff" 2>&1; then
  echo "check-openapi: $SPEC matches the handler annotations."
  exit 0
fi

{
  echo
  echo "────────────────────────────────────────────────────────────────────────────"
  echo "OpenAPI spec is out of date."
  echo
  echo "$SPEC does not match what swag $SWAG_VERSION generates from the"
  echo "// @Router annotations in internal/infra/http/handler/."
  echo
  echo "The spec is a generated artifact and the UI generates its API types from"
  echo "it, so hand-editing it — or changing a handler's annotations without"
  echo "regenerating — silently ships a client written against a server that does"
  echo "not exist."
  echo
  echo "Fix:"
  echo "    make swagger"
  echo "    git add $SPEC"
  echo
  echo "swag log (tail) — a 'cannot find type definition' here means the"
  echo "generator could not read a dependency and degraded silently:"
  tail -n 15 "$tmpdir/swag.log"
  echo
  echo "Diff (committed → regenerated), first 200 lines:"
  echo "────────────────────────────────────────────────────────────────────────────"
  head -n 200 "$tmpdir/spec.diff"
  lines="$(wc -l <"$tmpdir/spec.diff")"
  if [ "$lines" -gt 200 ]; then
    echo "... ($((lines - 200)) more diff lines)"
  fi
} >&2

exit 1
