/**
 * Code generated by api/cmd/gen-asset-types. DO NOT EDIT.
 *
 * Source of truth: api/configs/asset-types.yaml (RFC-042 §6.3).
 * Run `make generate-asset-types` in api/ to regenerate.
 *
 * The full registry (attributes, facets, columns, sections, relationships)
 * is served by GET /api/v1/asset-types; this file carries the closed sets
 * and labels for compile-time checks and for rendering before it loads.
 */

export const ASSET_REGISTRY_VERSION = '48862d766758d927'

export type AssetLens =
  | 'external_surface'
  | 'applications'
  | 'cloud_infra'
  | 'containers_k8s'
  | 'code'
  | 'identities'
  | 'data'
  | 'network'

export type AssetClass =
  | 'domain'
  | 'ip_address'
  | 'certificate'
  | 'service'
  | 'web_endpoint'
  | 'application'
  | 'host'
  | 'function'
  | 'cloud_account'
  | 'container'
  | 'cluster'
  | 'artifact_registry'
  | 'code_repo'
  | 'identity'
  | 'data_store'
  | 'network'
  | 'other'

export type RegistryAssetType =
  | 'domain'
  | 'subdomain'
  | 'ip_address'
  | 'certificate'
  | 'service'
  | 'http_service'
  | 'open_port'
  | 'discovered_url'
  | 'application'
  | 'website'
  | 'web_application'
  | 'api'
  | 'mobile_app'
  | 'host'
  | 'compute'
  | 'endpoint'
  | 'serverless'
  | 'cloud_account'
  | 'container'
  | 'kubernetes'
  | 'kubernetes_cluster'
  | 'kubernetes_namespace'
  | 'container_registry'
  | 'repository'
  | 'identity'
  | 'iam_user'
  | 'iam_role'
  | 'service_account'
  | 'database'
  | 'data_store'
  | 'storage'
  | 's3_bucket'
  | 'network'
  | 'vpc'
  | 'subnet'
  | 'firewall'
  | 'load_balancer'
  | 'unclassified'

export type LegacyAssetCategory =
  | 'external_surface'
  | 'application'
  | 'infrastructure'
  | 'network'
  | 'cloud'
  | 'data'
  | 'code'
  | 'identity'
  | 'other'

export const ASSET_LENSES: ReadonlyArray<{
  id: AssetLens
  label: string
  classes: readonly AssetClass[]
}> = [
  {
    id: 'external_surface',
    label: 'External surface',
    classes: ['domain', 'ip_address', 'certificate', 'service', 'web_endpoint'],
  },
  {
    id: 'applications',
    label: 'Applications',
    classes: ['application'],
  },
  {
    id: 'cloud_infra',
    label: 'Cloud & infrastructure',
    classes: ['host', 'function', 'cloud_account'],
  },
  {
    id: 'containers_k8s',
    label: 'Containers & Kubernetes',
    classes: ['container', 'cluster', 'artifact_registry'],
  },
  {
    id: 'code',
    label: 'Code',
    classes: ['code_repo'],
  },
  {
    id: 'identities',
    label: 'Identities',
    classes: ['identity'],
  },
  {
    id: 'data',
    label: 'Data',
    classes: ['data_store'],
  },
  {
    id: 'network',
    label: 'Network',
    classes: ['network'],
  },
]

export const ASSET_CLASSES: ReadonlyArray<{
  id: AssetClass
  label: string
  lens: AssetLens | null
}> = [
  { id: 'domain', label: 'Domain', lens: 'external_surface' },
  { id: 'ip_address', label: 'IP address', lens: 'external_surface' },
  { id: 'certificate', label: 'Certificate', lens: 'external_surface' },
  { id: 'service', label: 'Service', lens: 'external_surface' },
  { id: 'web_endpoint', label: 'Web endpoint', lens: 'external_surface' },
  { id: 'application', label: 'Application', lens: 'applications' },
  { id: 'host', label: 'Host', lens: 'cloud_infra' },
  { id: 'function', label: 'Function', lens: 'cloud_infra' },
  { id: 'cloud_account', label: 'Cloud account', lens: 'cloud_infra' },
  { id: 'container', label: 'Container', lens: 'containers_k8s' },
  { id: 'cluster', label: 'Cluster', lens: 'containers_k8s' },
  { id: 'artifact_registry', label: 'Artifact registry', lens: 'containers_k8s' },
  { id: 'code_repo', label: 'Code repository', lens: 'code' },
  { id: 'identity', label: 'Identity', lens: 'identities' },
  { id: 'data_store', label: 'Data store', lens: 'data' },
  { id: 'network', label: 'Network', lens: 'network' },
  { id: 'other', label: 'Other', lens: null },
]

/** The class of each type. Stored aliases keep their own class: see ASSET_ALIAS_CLASSES. */
export const ASSET_TYPE_CLASSES: Readonly<Record<RegistryAssetType, AssetClass>> = {
  domain: 'domain',
  subdomain: 'domain',
  ip_address: 'ip_address',
  certificate: 'certificate',
  service: 'service',
  http_service: 'service',
  open_port: 'service',
  discovered_url: 'web_endpoint',
  application: 'application',
  website: 'application',
  web_application: 'application',
  api: 'application',
  mobile_app: 'application',
  host: 'host',
  compute: 'host',
  endpoint: 'host',
  serverless: 'function',
  cloud_account: 'cloud_account',
  container: 'container',
  kubernetes: 'cluster',
  kubernetes_cluster: 'cluster',
  kubernetes_namespace: 'cluster',
  container_registry: 'artifact_registry',
  repository: 'code_repo',
  identity: 'identity',
  iam_user: 'identity',
  iam_role: 'identity',
  service_account: 'identity',
  database: 'data_store',
  data_store: 'data_store',
  storage: 'data_store',
  s3_bucket: 'data_store',
  network: 'network',
  vpc: 'network',
  subnet: 'network',
  firewall: 'network',
  load_balancer: 'network',
  unclassified: 'other',
}

/**
 * Stored (type, sub_type) pairs whose class differs from the type's class,
 * keyed `type/sub_type`: a host with sub_type serverless is a function.
 */
export const ASSET_ALIAS_CLASSES: Readonly<Record<string, AssetClass>> = {
  'service/discovered_url': 'web_endpoint',
  'host/serverless': 'function',
  'storage/container_registry': 'artifact_registry',
}

export const LEGACY_ASSET_CATEGORY_LABELS: Readonly<Record<LegacyAssetCategory, string>> = {
  external_surface: 'External Surface',
  application: 'Applications',
  infrastructure: 'Infrastructure',
  network: 'Network',
  cloud: 'Cloud',
  data: 'Data',
  code: 'Code',
  identity: 'Identity',
  other: 'Other',
}
